# Uncomment the next line to define a global platform for your project
  platform :ios, '16.0'

target 'TestingIOSApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestingIOSApp

  pod 'RealmSwift'

  target 'TestingIOSAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestingIOSAppUITests' do
    # Pods for testing
  end

end
